i = int(input('Digite um número para ver sua tabuada: '))
print('_______________')
print('| {}x1 = {}'.format(i, i*1))
print('| {}x2 = {}'.format(i, i*2))
print('| {}x3 = {}'.format(i, i*3))
print('| {}x4 = {}'.format(i, i*4))
print('| {}x5 = {}'.format(i, i*5))
print('| {}x6 = {}'.format(i, i*6))
print('| {}x7 = {}'.format(i, i*7))
print('| {}x8 = {}'.format(i, i*8))
print('| {}x9 = {}'.format(i, i*9))
print('| {}x10 = {}'.format(i, i*10))
print('---------------')